### ISSUE TITLE
Use Gradle properties in docker-compose.yml.peb

### ISSUE THREAD

**Issue by piandrus-cog** [Cognifide/gradle-environment-plugin#3]
Hello,

In `docker-compose.yml.peb` I can use values from `docker`, `system` and `env`. I would like to also be able to use Gradle properties, e.g. from `~/.gradle/gradle.properties`.

It turns out that it is possible to use `{{docker.environment.project.properties['yourprop']}}` (thanks, @pun-ky !). A nice improvement would be to have them accessible with shorter path.

**Comment by pun-ky** [comment]
yep, it will be done in next version. thanks for reporting it @piandrus-cog 

probably as `{{project.properties['yourprop']}}`

**Comment by pun-ky** [comment]
done
