### ISSUE TITLE
Hosts jar execution error

### ISSUE THREAD

**Issue by pun-ky** [Cognifide/gradle-environment-plugin#8]
```
java -jar /Users/xxx.yyy/Documents/Projects/foo/gapenv/.gradle/environment/hosts/hosts.jar
```

works but `environmentHosts` not:  

```
/Users/xxx.yyy/Documents/Projects/foo/gapenv/.gradle/environment/hosts/hosts.sh
Successfully started process 'command 'sh''
0:297: execution error: Error: Unable to access jarfile /Users/xxx.yyy/Documents/Projects/foo/gapenv/.gradle/environment/hosts/hosts.jar (1)
> Task :environmentHosts FAILED
```

**Comment by pun-ky** [comment]
moving project to ~ fixed the problem. chmod +x or 0777 not helping.

**Comment by mierzwid** [comment]
On new MacOSX `/Users/user.name/Documents` path is special and requires additional privileges. In iTerm if I cd into that directory I am asked if I want to give access to iTerm. In the case of our shell script run via Gradle, there is no propt - it just fails.
